version: "3.9" 

services:
  mongo:
    container_name: mongodb-docker
    image: mongodb/mongodb-community-server:latest
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    
  Backend:
    container_name: backend-account-manager
    restart: unless-stopped
    image: backend-account-manager
    build: ./Backend
    ports:
      - 8081:8081
    volumes:
      - ./Backend:/user/src/server
      - /app/node_modules
      - ./Backend:/app:/controllers
      - ./Backend:/app:/documents
    networks:
      - app-network
    environment:
      - NODE_ENV:production
    env_file: ./Backend/.env
    depends_on: 
      - mongo


  frontend:
    container_name: frontend-account-manager
    restart: unless-stopped
    image: frontend-account-manager
    build: ./frontend
    volumes:
      - ./frontend:/src
      - /app/node_modules
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - Backend
      
networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local

